//LOGIN 
export const ADD_USERNAME = "ADD_USERNAME";
export const ADD_USER_PIN = "ADD_USER_PIN";


//USER
export const REMEMBER_ME_CHANGED = "REMEMBER_ME_CHANGED";
export const USER_ID_CHANGED = "USER_ID_CHANGED";
export const IS_LOGGED = "IS_LOGGED";
export const ACCESS_TOKEN_CHANGED = "ACCESS_TOKEN_CHANGED";
export const USER_NAME_CHANGED = "USER_NAME_CHANGED";
export const SELECTED_OPU_CHANGED = "SELECTED_OPU_CHANGED";
export const SELECTED_OPU_ID_CHANGED = "SELECTED_OPU_ID_CHANGED";
export const SELECTED_EVENT_CHANGED = "SELECTED_EVENT_CHANGED";
export const SELECTED_EVENT_ID_CHANGED = "SELECTED_EVENT_ID_CHANGED";
export const FETCH_OPUS_LIST = "FETCH_OPUS_LIST";
export const FETCH_OPUS_LIST_SUCCESS = "FETCH_OPUS_LIST_SUCCESS";
export const FETCH_OPUS_LIST_ERROR = "FETCH_OPUS_LIST_ERROR";
export const FETCH_EVENT_LIST = "FETCH_EVENT_LIST";
export const FETCH_EVENT_LIST_SUCCESS = "FETCH_EVENT_LIST_SUCCESS";
export const FETCH_EVENT_LIST_ERROR = "FETCH_EVENT_LIST_ERROR";
export const INTERNET_CONNECTIVITY_CHANGED = "INTERNET_CONNECTIVITY_CHANGED";
export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
export const UPLOAD_USER_PIC = "UPLOAD_USER_PIC";
export const UPLOAD_USER_PIC_SUCCESS = "UPLOAD_USER_PIC_SUCCESS";
export const UPLOAD_USER_PIC_FAILURE = "UPLOAD_USER_PIC_FAILURE";

//WORKLIST
export const WORKLIST_CHANGED = "WORKLIST_CHANGED";

//PROFILE
export const FETCH_PROFILE = "FETCH_PROFILE"
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS"
export const FETCH_PROFILE_FAILURE = "FETCH_PROFILE_FAILURE"
export const UPLOAD_PROFILE_PIC = "UPLOAD_PROFILE_PIC"
export const UPLOAD_PROFILE_PIC_SUCCESS = "UPLOAD_PROFILE_PIC_SUCCESS"
export const UPLOAD_PROFILE_PIC_FAILURE = "UPLOAD_PROFILE_PIC_FAILURE"

//WORKLIST
export const FETCH_WORKLIST = "FETCH_WORKLIST"
export const FETCH_WORKLIST_SUCCESS = "FETCH_WORKLIST_SUCCESS"
export const FETCH_WORKLIST_FAILURE = "FETCH_WORKLIST_FAILURE"
export const FETCH_WORKLIST_PHASES = "FETCH_WORKLIST_PHASES"
export const FETCH_WORKLIST_PHASES_SUCCESS = "FETCH_WORKLIST_PHASES_SUCCESS"
export const FETCH_WORKLIST_PHASES_FAILURE = "FETCH_WORKLIST_PHASES_FAILURE"
export const SAVE_BOOKMARK = "SAVE_BOOKMARK"
export const SAVE_BOOKMARK_SUCCESS = "SAVE_BOOKMARK_SUCCESS"
export const SAVE_BOOKMARK_FAILURE = "SAVE_BOOKMARK_FAILURE"
export const GET_TASK = "GET_TASK"
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS"
export const GET_TASK_FAILURE = "GET_TASK_FAILURE"
export const STORE_WORKLIST = "STORE_WORKLIST"
export const GET_WORKLIST = "GET_WORKLIST"

//TASKLIST
export const FETCH_TASKLIST = "FETCH_TASKLIST"
export const FETCH_TASKLIST_SUCCESS = "FETCH_TASKLIST_SUCCESS"
export const FETCH_TASKLIST_FAILURE = "FETCH_TASKLIST_FAILURE"
export const FETCH_TASK = "FETCH_TASK"
export const FETCH_TASK_SUCCESS = "FETCH_TASK_SUCCESS"
export const FETCH_TASK_FAILURE = "FETCH_TASK_FAILURE"
export const UPDATE_TASK = "UPDATE_TASK"
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS"
export const UPDATE_TASK_FAILURE = "UPDATE_TASK_FAILURE"
export const UPDATE_SUBTASK_STATUS = "UPDATE_SUBTASK_STATUS"
export const SELECT_ALL_STATUS_CHANGED = "SELECT_ALL_STATUS_CHANGED"
export const MUTATE_TASKLIST = "MUTATE_TASKLIST"

// ACTIVITY LOGS
export const FETCH_ACTIVITY_LOGS = "FETCH_ACTIVITY_LOGS"
export const FETCH_ACTIVITY_LOGS_SUCCESS = "FETCH_ACTIVITY_LOGS_SUCCESS"
export const FETCH_ACTIVITY_LOGS_FAILURE = "FETCH_ACTIVITY_LOGS_FAILURE"
export const UPDATE_ACTIVITY_LOGS = "UPDATE_ACTIVITY_LOGS"


//WORKLIST FILTER
export const GET_WORKLIST_FILTER = "GET_WORKLIST_FILTER"
export const GET_WORKLIST_FILTER_SUCCESS = "GET_WORKLIST_FILTER_SUCCESS"
export const GET_WORKLIST_FILTER_FAILURE = "GET_WORKLIST_FILTER_FAILURE"
export const STORE_TASK = "STORE_TASK"

//TASKLIST FILTER
export const GET_TASKLIST_FILTER = "GET_TASKLIST_FILTER"
export const GET_TASKLIST_FILTER_SUCCESS = "GET_TASKLIST_FILTER_SUCCESS"
export const GET_TASKLIST_FILTER_FAILURE = "GET_TASKLIST_FILTER_FAILURE"

//OFFLINE MODE
export const OFFLINE_MODE_CHANGED = "OFFLINE_MODE_CHANGED";
export const ADD_OFFLINE_DATA = "ADD_OFFLINE_DATA";
export const RESET_OFFLINE_DATA = "RESET_OFFLINE_DATA";
export const OFFLINE_DATA_STATUS_CHANGED = "OFFLINE_DATA_STATUS_CHANGED";
export const OFFLINE_PROGRESS_CHANGED = "OFFLINE_PROGRESS_CHANGED";
export const OFFLINE_DATA_CHANGED = "OFFLINE_DATA_CHANGED";

//SAVED
export const FETCH_SAVED_WORKLIST = "FETCH_SAVED_WORKLIST"
export const FETCH_SAVED_WORKLIST_SUCCESS = "FETCH_SAVED_WORKLIST_SUCCESS"
export const FETCH_SAVED_WORKLIST_FAILURE = "FETCH_SAVED_WORKLIST_FAILURE"

//WORKSHOP
export const FETCH_WORKSHOP = "FETCH_WORKSHOP"
export const FETCH_WORKSHOP_SUCCESS = "FETCH_WORKSHOP_SUCCESS"
export const FETCH_WORKSHOP_FAILURE = "FETCH_WORKSHOP_FAILURE"

// Temp
export const SET_WCS_VERIFIER = "SET_WCS_VERIFIER"
